--Citizen.CreateThread(function()
--    exports["PolyZone"]:AddCircleZone("huntingsales", vector3(-773.28, 5596.95, 33.49), 2.0, {
--        useZ = true,
--        debugPoly= true,
--    })
--end)